title: Bagus Adhi Wicaksono
logo: /assets/img/round_profile.png
#description: An adaptive, creative, and detail-oriented fresh graduate computer student from Airlangga University who is experienced in problem-solving and developing strong partnerships. Ready to make a meaningful impact with the combination of data expertise and computer skills.
show_downloads: true
theme: jekyll-theme-minimal
